name: Build and Push Container Images

on:
  workflow_call:
  workflow_dispatch:

permissions:
  packages: write

env:
  ContainerRegistry: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [server, agent, player]
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.component }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: containers/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            COMPONENT=${{ matrix.component }}
          tags: |
            ${{ env.ContainerRegistry }}/${{ env.IMAGE_NAME }}-${{ matrix.component }}:${{ github.ref_name }}
