name: Release

# Trigger the workflow only when a new tag starting with "v" is pushed (e.g., v1.0.0)
on:
  push:
    tags:
      - v*

# Prevent duplicate jobs running for same tag; cancel in-progress if newer tag is pushed
concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  # Run the main Rust CI checks (tests, formatting, lint, etc.)
  run-rust-ci:
    uses: ./.github/workflows/run-ci.yml

  # Run Rust documentation lint checks
  run-doc-lint:
    uses: ./.github/workflows/run-doc.yml

  # Run YAML syntax and structure validation
  run-yaml-validation:
    uses: ./.github/workflows/run-validate.yml

  # Generate license reports using cargo-about
  run-license-report:
    uses: ./.github/workflows/run-license-check.yml

  # Main job to gather reports and publish artifacts to the GitHub release
  tag_release_artifacts:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Collect and upload release artifacts
    runs-on: ubuntu-latest
    needs:
      - run-rust-ci
      - run-doc-lint
      - run-yaml-validation
      - run-license-report
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download deny report
        uses: actions/download-artifact@v4
        with:
          name: deny-report
          path: dist/reports/deny/

      - name: Download fmt report
        uses: actions/download-artifact@v4
        with:
          name: fmt-report
          path: dist/reports/fmt/

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: dist/tests/

      - name: Download license report
        uses: actions/download-artifact@v4
        with:
          name: license-report
          path: dist/licenses/

      - name: Upload deny report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_deny_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/reports/deny/deny_summary.md
          tag: ${{ github.ref }}

      - name: Upload fmt report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_fmt_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/reports/fmt/fmt_summary.md
          tag: ${{ github.ref }}

      - name: Upload test report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_test_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/tests/test_summary.xml
          file_glob: true
          tag: ${{ github.ref }}

      - name: Upload license report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_license_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/licenses/*.html
          file_glob: true
          tag: ${{ github.ref }}

      - name: Gets latest created release info
        id: latest_release_info
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload README to release
        uses: svenstaro/upload-release-action@v2
        id: upload_readme
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: README.md
          tag: ${{ github.ref }}

      - name: Upload Coding Guidelines to release
        uses: svenstaro/upload-release-action@v2
        id: upload_coding_guidelines
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/coding-rule.md
          tag: ${{ github.ref }}

      - name: Upload Release Process to release
        uses: svenstaro/upload-release-action@v2
        id: upload_release_process
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .github/workflows/release.yml
          tag: ${{ github.ref }}

      - name: Archive doc folder
        shell: bash
        run: |
          tar czf doc-archive.tar.gz doc/

      - name: Upload doc archive to release
        uses: svenstaro/upload-release-action@v2
        id: upload_doc
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: doc-archive.tar.gz
          tag: ${{ github.ref }}

      - name: Collect quality artifacts with quevee
        id: quevee_manifest
        uses: eclipse-dash/quevee@v1
        with:
          release_url: ${{ steps.latest_release_info.outputs.html_url }}
          artifacts_readme: ${{ steps.upload_readme.outputs.browser_download_url }}
          artifacts_coding_guidelines: ${{ steps.upload_coding_guidelines.outputs.browser_download_url }}
          artifacts_release_process: ${{ steps.upload_release_process.outputs.browser_download_url }}
          artifacts_documentation: ${{ steps.upload_doc.outputs.browser_download_url }}
          artifacts_requirements: ${{ steps.upload_doc.outputs.browser_download_url }}
          artifacts_testing: ${{ steps.upload_test_report.outputs.browser_download_url }}, ${{ steps.upload_license_report.outputs.browser_download_url }}, ${{ steps.upload_fmt_report.outputs.browser_download_url }}, ${{ steps.upload_deny_report.outputs.browser_download_url }}

      - name: Upload quality manifest to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee_manifest.outputs.manifest_file }}
          tag: ${{ github.ref }}

  build-and-push-container:
    name: Build and Push Container Image
    uses: ./.github/workflows/build-container.yml
    needs:
      - tag_release_artifacts
    permissions:
      packages: write
