name: Release

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  run-rust-ci:
    uses: ./.github/workflows/run-ci.yml

  run-doc-lint:
    uses: ./.github/workflows/run-doc.yml

  run-yaml-validation:
    uses: ./.github/workflows/run-validate.yml

  tag_release_artifacts:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Collect and upload release artifacts
    runs-on: ubuntu-latest
    needs:
      - run-rust-ci
      - run-doc-lint
      - run-yaml-validation
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download deny report
        uses: actions/download-artifact@v4
        with:
          name: deny-report
          path: dist/reports/deny/

      - name: Download fmt report
        uses: actions/download-artifact@v4
        with:
          name: fmt-report
          path: dist/reports/fmt/

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: dist/reports/test/

      # - name: Download docs report
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: docs-report
      #     path: dist/reports/docs/

      - name: Upload deny report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_deny_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/reports/deny/deny_summary.md
          tag: ${{ github.ref }}

      - name: Upload fmt report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_fmt_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/reports/fmt/fmt_summary.md
          tag: ${{ github.ref }}

      - name: Upload test report to release
        uses: svenstaro/upload-release-action@v2
        id: upload_test_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/reports/test/test_summary.md
          tag: ${{ github.ref }}

      # - name: Upload docs report to release
      #   uses: svenstaro/upload-release-action@v2
      #   id: upload_docs_report
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: dist/reports/docs/docs_report.md
      #     tag: ${{ github.ref }}

      - name: Gets latest created release info
        id: latest_release_info
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect quality artifacts with quevee
        id: quevee_manifest
        uses: eclipse-dash/quevee@v1
        with:
          release_url: ${{ steps.latest_release_info.outputs.html_url }}
          artifacts_testing: ${{ steps.upload_test_report.outputs.browser_download_url }}
          artifacts_formatting: ${{ steps.upload_fmt_report.outputs.browser_download_url }}
          artifacts_licenses: ${{ steps.upload_deny_report.outputs.browser_download_url }}
          # artifacts_docs: ${{ steps.upload_docs_report.outputs.browser_download_url }}

      - name: Upload quality manifest to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee_manifest.outputs.manifest_file }}
          tag: ${{ github.ref }}
